add_newline =	true

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[character]
success_symbol = "[⮞](bold 9)"
error_symbol = "[✗](bold red)"

[directory]
style = "bold yellow"
read_only = ":ro"
read_only_style = "yellow"
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = ": [$symbol$branch]($style) "

[line_break]
disabled = false

